#!/bin/sh

CLAZZ_PATH=magic-conch-shell.jar
MAIN_CLASS=com.alteredmechanism.mcsh.Main 

# This can happen if a Windows version of Java is run in Cygwin, Mingw, or Git Bash.
isRunningOnWindows()
{
  [ -n "$COMSPEC" -o -n "$PATHEXT" ]
}


if isRunningOnWindows
then
  # Switch colons to semicolons in classpath.
  CLAZZ_PATH="${CLAZZ_PATH//:/;}"
fi

java -classpath $CLAZZ_PATH $MAIN_CLASS "$@"
